version: "3.9"

services:
  frontend:
    build: ./astro-frontend
    ports:
      - "4321:4321"
    depends_on:
      - backend

  backend:
    build: ./nest-backend
    ports:
      - "3000:3000"
    env_file:
      - ./nest-backend/.env
    depends_on:
      - mysql

  ml-api:
    build: ./ml-api
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: backend_root
      MYSQL_DATABASE: laboratorio-evaluaciones
      MYSQL_USER: backend_user
      MYSQL_PASSWORD: backend_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
